apiVersion: v1
data:
  ACCEPT_EULA: "Y"
  PHP_IDE_CONFIG: serverName=app
  SA_PASSWORD: Pa$$w0rd
  XDEBUG_CONFIG: remote_enable=On remote_autostart=On remote_connect_back=Off remote_host=docker.for.win.localhost
    remote_port=9000
kind: ConfigMap
metadata:
  labels:
    app: database-env
  name: database-env

---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app : database
  name: database
spec:
  replicas: 1
  selector:
    matchLabels:
      app: database
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: database
    spec:
      containers:
      - env:
        - name: ACCEPT_EULA
          valueFrom:
            configMapKeyRef:
              key: ACCEPT_EULA
              name: database-env
        - name: PHP_IDE_CONFIG
          valueFrom:
            configMapKeyRef:
              key: PHP_IDE_CONFIG
              name: database-env
        - name: SA_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: SA_PASSWORD
              name: database-env
        - name: XDEBUG_CONFIG
          valueFrom:
            configMapKeyRef:
              key: XDEBUG_CONFIG
              name: database-env
        image: mcr.microsoft.com/mssql/server:2017-latest
        name: database
        ports:
        - containerPort: 1433
        resources:
          limits:
            memory: "4294967296"
          requests:
            memory: "2147483648"
        volumeMounts:
        - mountPath: /var/opt/mssql/data
          name: db
      volumes:
      - name: db
        persistentVolumeClaim:
          claimName: database
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database
spec:
  ports:
  - name: "tcp"
    port: 1433
    targetPort: 1433
    nodePort: 31430
  type: NodePort
  selector:
    app: database

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: ebs-storage

