apiVersion: v1
kind: Service
metadata:
  labels:
    app: database
  name: database
spec:
  ports:
  - name: "tcp"
    port: 1433
    targetPort: 1433
    nodePort: 31430
  type: NodePort
  selector:
    app: database
