apiVersion: apps/v1
kind: Deployment
metadata:
  name: agent-deployment
  #  annotations: 
  #  iam.amazon.com/role: k8s-pods-s3-role
spec:
  replicas: 1 
  selector:
    matchLabels:
      app: agent-pod
  template:
    metadata:
      annotations:
              #        iam.amazonaws.com/role: arn:aws:iam::430723739319:role/saad-s3-role
              #         iam.amazonaws.com/role: arn:aws:iam::674528447826:role/k8s-pods-s3-role
      labels:
        app: agent-pod
    spec:
      containers:
      - name: agent-container
        image: 582311285210.dkr.ecr.eu-west-2.amazonaws.com/teamcity:teamcity-agent 
        env:
          - name: SERVER_URL
            value: http://teamcity
            # - name: AWS_ACCESS_KEY
            #valueFrom: 
            #  configMapKeyRef:
            #   key: AWS_ACCESS_KEY
            #   name: env
            #magePullSecrets:
            # name: ecregent
