kind: ServiceAccount
apiVersion: v1
metadata:
  name: sa
  namespace: ci-server
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: teamcityrole
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: teamcityrole
subjects:
- kind: ServiceAccount
  name: default
  namespace: ci-server

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: teamcityrole
rules:
- apiGroups:
  - ""
  resources:
  - services
  - events
  - endpoints
  - pods
  - nodes
  - componentstatuses
  - namespaces
  - deployments  
  verbs:
  - get
  - list
  - watch
  - create 
  - delete  
- apiGroups:
  - ""
  resources:
  - configmaps
  #resourceNames:
  #- datadogtoken             # Kubernetes event collection state
  #- datadog-leader-election  # Leader election token
  verbs:
  - get
  - update
- apiGroups:  # To create the leader election token
  - ""
  resources:
  - configmaps
  verbs:
  - create
- nonResourceURLs:
  - "/version"
  - "/healthz"
  verbs:
  - get
- apiGroups:  # Kubelet connectivity
  - ""
  resources:
  - nodes/metrics
  - nodes/spec
  - nodes/proxy
  verbs:
  - get
